
set terminal png size 800,800
set output 'primegaps.png'
set title 'Prime Gaps'
unset key
set datafile separator comma
plot 'gaps_0.dat' with lines lc rgb "purple", \
'gaps_1.dat' with lines lc rgb "purple", \
'gaps_2.dat' with lines lc rgb "purple", \
'gaps_3.dat' with lines lc rgb "purple", \
'gaps_4.dat' with lines lc rgb "purple", \
'gaps_5.dat' with lines lc rgb "purple", \
'gaps_6.dat' with lines lc rgb "purple", \
'gaps_7.dat' with lines lc rgb "purple", \
'gaps_8.dat' with lines lc rgb "purple", \
'gaps_9.dat' with lines lc rgb "purple", \
'gaps_10.dat' with lines lc rgb "purple", \
'gaps_11.dat' with lines lc rgb "purple", \
'gaps_12.dat' with lines lc rgb "purple", \
'gaps_13.dat' with lines lc rgb "purple", \
'gaps_14.dat' with lines lc rgb "purple", \
'gaps_15.dat' with lines lc rgb "purple", \
'gaps_16.dat' with lines lc rgb "purple", \
'gaps_17.dat' with lines lc rgb "purple", \
'gaps_18.dat' with lines lc rgb "purple", \
'gaps_19.dat' with lines lc rgb "purple", \
'gaps_20.dat' with lines lc rgb "purple", \
'gaps_21.dat' with lines lc rgb "purple", \
'gaps_22.dat' with lines lc rgb "purple", \
'gaps_23.dat' with lines lc rgb "purple", \
'gaps_24.dat' with lines lc rgb "purple", \
'gaps_25.dat' with lines lc rgb "purple", \
'gaps_26.dat' with lines lc rgb "purple", \
'gaps_27.dat' with lines lc rgb "purple", \
'gaps_28.dat' with lines lc rgb "purple", \
'gaps_29.dat' with lines lc rgb "purple", \
'gaps_30.dat' with lines lc rgb "purple", \
'gaps_31.dat' with lines lc rgb "purple", \
'gaps_32.dat' with lines lc rgb "purple", \
'gaps_33.dat' with lines lc rgb "purple", \
'gaps_34.dat' with lines lc rgb "purple", \
'gaps_35.dat' with lines lc rgb "purple", \
'gaps_36.dat' with lines lc rgb "purple", \
'gaps_37.dat' with lines lc rgb "purple", \
'gaps_38.dat' with lines lc rgb "purple", \
'gaps_39.dat' with lines lc rgb "purple", \
'gaps_40.dat' with lines lc rgb "purple", \
'gaps_41.dat' with lines lc rgb "purple", \
'gaps_42.dat' with lines lc rgb "purple", \
'gaps_43.dat' with lines lc rgb "purple", \
'gaps_44.dat' with lines lc rgb "purple", \
'gaps_45.dat' with lines lc rgb "purple", \
'gaps_46.dat' with lines lc rgb "purple", \
'gaps_47.dat' with lines lc rgb "purple", \
'gaps_48.dat' with lines lc rgb "purple", \
'gaps_49.dat' with lines lc rgb "purple", \
'gaps_50.dat' with lines lc rgb "purple", \
'gaps_51.dat' with lines lc rgb "purple", \
'gaps_52.dat' with lines lc rgb "purple", \
'gaps_53.dat' with lines lc rgb "purple", \
'gaps_54.dat' with lines lc rgb "purple", \
'gaps_55.dat' with lines lc rgb "purple", \
'gaps_56.dat' with lines lc rgb "purple", \
'gaps_57.dat' with lines lc rgb "purple", \
'gaps_58.dat' with lines lc rgb "purple", \
'gaps_59.dat' with lines lc rgb "purple", \
'gaps_60.dat' with lines lc rgb "purple", \
'gaps_61.dat' with lines lc rgb "purple", \
'gaps_62.dat' with lines lc rgb "purple", \
'gaps_63.dat' with lines lc rgb "purple", \
'gaps_64.dat' with lines lc rgb "purple", \
'gaps_65.dat' with lines lc rgb "purple", \
'gaps_66.dat' with lines lc rgb "purple", \
'gaps_67.dat' with lines lc rgb "purple", \
'gaps_68.dat' with lines lc rgb "purple", \
'gaps_69.dat' with lines lc rgb "purple", \
'gaps_70.dat' with lines lc rgb "purple", \
'gaps_71.dat' with lines lc rgb "purple", \
'gaps_72.dat' with lines lc rgb "purple", \
'gaps_73.dat' with lines lc rgb "purple", \
'gaps_74.dat' with lines lc rgb "purple", \
'gaps_75.dat' with lines lc rgb "purple", \
'gaps_76.dat' with lines lc rgb "purple", \
'gaps_77.dat' with lines lc rgb "purple", \
'gaps_78.dat' with lines lc rgb "purple", \
'gaps_79.dat' with lines lc rgb "purple", \
'gaps_80.dat' with lines lc rgb "purple", \
'gaps_81.dat' with lines lc rgb "purple", \
'gaps_82.dat' with lines lc rgb "purple", \
'gaps_83.dat' with lines lc rgb "purple", \
'gaps_84.dat' with lines lc rgb "purple", \
'gaps_85.dat' with lines lc rgb "purple", \
'gaps_86.dat' with lines lc rgb "purple", \
'gaps_87.dat' with lines lc rgb "purple", \
'gaps_88.dat' with lines lc rgb "purple", \
'gaps_89.dat' with lines lc rgb "purple", \
'gaps_90.dat' with lines lc rgb "purple", \
'gaps_91.dat' with lines lc rgb "purple", \
'gaps_92.dat' with lines lc rgb "purple", \
'gaps_93.dat' with lines lc rgb "purple", \
'gaps_94.dat' with lines lc rgb "purple", \
'gaps_95.dat' with lines lc rgb "purple", \
'gaps_96.dat' with lines lc rgb "purple", \
'gaps_97.dat' with lines lc rgb "purple", \
'gaps_98.dat' with lines lc rgb "purple", \
'gaps_99.dat' with lines lc rgb "purple", \
'gaps_100.dat' with lines lc rgb "purple"
